checks:
    javascript: true
filter:
    excluded_paths:
        - tests/*
        - node_modules/*
        - template/*
        - src/2.0/templates/*
build:
    dependencies:
        before:
            - npm install --dev
            - npm install mocha
            - npm install -g mocha
            - npm install -g istanbul
            - npm install istanbul   # or add it as part of your package.json
    tests:
        override:
            -
                command: 'node ./node_modules/istanbul/lib/cli.js cover _mocha --report clover ./tests/tests/*Test.js'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            other:
                after_type_cast: false