checks:
    javascript: true
filter:
    excluded_paths:
        - tests/*
        - node_modules/*
build:
    dependencies:
        before:
            - npm install istanbul   # or add it as part of your package.json
    tests:
        override:
            -
                command: 'istanbul cover _mocha --report clover test.js'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
checks:
    javascript: true
coding_style:
    javascript:
        spaces:
            around_operators:
                concatenation: true
            other:
                after_type_cast: false